[0_(1)=T1_RabLike(192){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(164)********************************************************************************************************************************************************************

$1=164(164):
>consensus seq
{()KEFKIVLVGDGGVGKSTLLNRLLGGEFAEDYGPTIGIDFYTKTVEVDGKGVKLQLWDTPGQEDFRALWISYYRGADGVILVVDATDRESFEELKEWLEEILRLALEGIPIILVGNKIDLLDAREVSEEEGEALAKERGVPFFETSAKTGENVDELFEALAREIL()}*

$2=164(164):
>T1_RabLike consensus seq
{()YEFKLVVVGDSGVGKTSLLLRFVTGEFPEEYDPTIGVDFYTKTVEVDGKTVKLQIWDTAGQERFRALRPLYYRGADGALLVYDITDRESFENVKKWLEEIRRHAGPNVPIVLVGNKCDLEDERQVSTEEGEAFAKELGLPFFETSAKTGENVEEAFEELARKIL()}*

$3=164(164):
>FYpivot consensus seq
{()YEFKLVVVGDGGVGKTALLLRFTTGEFVEDYDPTIGVDFYTKTVEVDGKTVKLQIWDTAGQERFRALRPLYYRGADGALLVYDITSRESFENVKKWLEEIRRVADDNVPIVLVGNKCDLEDERVVSTEEGEAFAKELGLPFLETSAKTAINVEEAFLELARKIL()}*

$4=164(164):
>gtpases consensus seq for GTPasesGold8.cma
{()REVKVVLVGHGGVGKSTLLNRLTGDEFVASYEPTIGITIYTKTVEVDGKGVKFTIWDTAGQEDYRRLWIAYYRQADGAILVVDATDPDSFENVEEWRKELREHLNEGVPIILVGNKIDLVDERLVEKEEAEALARDDGVPYIETSAKTGENVDELFDWLAREIL()}*

$5=164(164):
>DirA  {|5(29)|}consensus seq for DIRA/DirAGold.cma
{()NDYRVVVFGAGGVGKSSLVLRFVKGTFRETYIPTI-EDTYRQVISCDKNVCTLQITDTTGSHQFPAMQRLSISKGHAFILVYSVTSKQSLEELKPIYEQIKEIkgDVENIPIMLVGNKCD-ETQREVSSSEGEAQAKTWKCAFMETSAKTNHNVTELFQELLNLEK()}*

$6=163(164):
>Rad consensus seq for RAD/RadGold.cma
{()GVYKVVLLGEPGVGKSSLARIF--AGVEDSHECEEAGDTYERTIVVDGEEATLVVYDIWEQDDGSWLQDHCMQMGDAYVIVYSVTDRSSFEKASELRIQLRRArQTEDIPIILVGNKSDLVRSREVSVEEGRACAVVFDCKFIETSAALHHNVKELFEGIVRQIR()}*

$7=164(164):
>RalA  consensus seq for RALA/RalAGold.cma
{()ALHKVIMVGSGGVGKSALTLQFMYDEFVEDYEPTKXADSYRKKVVLDGEEVQIDILDTAGQEDYAAIRDNYFRSGEGFLCVFSITEDESFAATAEFREQILRVKEDEIPFLLVGNKSDLEDKRQVSLEEAQARAEEWGVPYVETSAKTRENVDKVFFDLMREIR()}*

$8=164(164):
>Ral consensus seq for RAL/RalGold.cma
{()REYKLVVVGGGGVGKSALTIQFIQSHFVDDYDPTIXEDSYRKQCVIDGEEAQLDILDTAGQEEYSAMREQYMRTGEGFLLVFSITDRESFEEIAKFRQQILRVDRDEFPMILVGNKCDLEEERQVSREEGQELARQLGVPYIETSAKTRINVDKAFFDLVREIR()}*

$9=165(164):
>Rap1 consensus seq for RAP1/Rap1Gold.cma
{()REYKLVVLGSGGVGKSALTVQFVQGIFVEKYDPTI-EDSYRKQVEVDGQQCMLEILDTAGTEQFTAMRDLYMKNGQGFVLVYSITAQSTFNDLQDLREQILRVKDtDDVPMVLVGNKCDLEDERVVGKDQGQNLARQFNnCAFLETSAKNKINVNEIFYDLVRQIN()}*

$10=164(164):
>Rap2A consensus seq for RAP2A/Rap2aGold.cma
{()REYKLVVLGSGGVGKSALTVQFVQGIFVEKYDPTI-EDSYRKQVEVDGQQCLLEILDTAGTEQFTAMRDLYMKNGQGFLLVYSITSQSTFNDLQDFREQILRVkDTDNVPMVLVGNKCDLEDERVVGKEEGEALAKKFGCPFLETSAKTRINVDEAFYDLVREIN()}*

$11=164(164):
>RasLike consensus seq for RAS_LIKE/RasLikeGold.cma
{()TEYRVAVLGAPGVGKTALISQFLFGEFPERYRPTIGEELYRKAVLLDGAVYTLSILDTAGSEEFPAMRDLSIQTSDAFVLVYSIDDPDSFDEVKALRERILEVGKKEVPIVVVGNKRDLQRERQVPREELAALVRDWNCGYIETSAKTNWNVLELFRELLRQIR()}*

$12=163(164):
>Ras  {|2(7)|}consensus  seq for RAS/RasGold.cma
{()TEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTI-EDSYRKQVVIDGETCLLDILDTAGQEEYSAMRDQYMRTGEGFLLVYAITSRKSFEEISTYREQILRVkDADDVPMVLVGNKCDL-AERAVSSREGEDLARSFGIPYIETSAKTRQGVEDAFYTLVREIR()}*

$13=164(164):
>RheB consensus
{()KERKIAIMGYRSVGKSSLTIQFVEGQFVDSYDPTI-ENTFTKTTKVNGQEYDLKLVDTAGQDEYSIFPQQYSMDIHGYVLVYSITSQKSFEVIKIIYDKLLDMtGKVHVPIVLVGNKKDLHMERVVSTEEGKKLAESWKAAFLEASAKQNESVVDVFKRIILEIE()}*

$14=165(164):
>Rit consensus seq for RIT/RitGold.cma
{()REYKVVMLGAGGVGKSAMTMQFISHQFPDYHDPTIVEDAYKTQVRIDNEPAYLDILDTAGQAEFTAMRDQYMRGGEGFIICYSVTDRQSFQEAAEFKELIFRVrHTYDIPLVLVGNKIDLEQFRQVSTEEGLSLAREFNCPFFETSAALRYYIDDAFHALVREIR()}*

$15=164(164):
>RabFamA consensus seq
{()YLFKIVLIGDSGVGKTSLLLRFTDGTFSENYKSTIGVDFKSKTIEVDGKKVKLQIWDTAGQERFRSITSSYYRGAHGAILVYDITNRESFENLEKWLEEIKEYAGPNVPIILVGNKSDLEDKRQVSTEEAEEFAKENGLPFFETSAKTGENVEEAFETLAKEIL()}*

$16=164(164):
>Plant1Rab  {|9(0)|}consensus seq for PLANT1RAB/Plant1RabGold.cma
{()YLFKLLLIGDSGVGKSSLLLSFTSDSFEDLDSPTIGVDFKVKHVTVGGKKLKLTIWDTAGQERFRTLTSSYYRGAQGIILVYDVTRRETFTNLSDWAKEIDLYSNQDCIKMLVGNKVDKESERVVTKKEGIAFAREYGCLFLECSAKTRVNVEQCFEELVLKIL()}*

$17=164(164):
>PlantRab11 consensus seq for PLANT_RAB11/PlantRab11Gold.cma
{()YVFKVVLIGDSAVGKSQLLARFARNEFSLDSKATIGVEFQTRTLVIDGKEVKAQIWDTAGQERYRAVTSAYYRGAVGALLVYDITRRQTFDHIPRWLEELRTHADKNIVIMLVGNKSDLEDIRAVSTEDAKEFAEKEGLFFMETSALDATNVETAFETVLTEIY()}*

$18=164(164):
>Rab11Like consensus seq for RAB11LIKE/Rab11LikeGold.cma
{()YLFKIVLIGDSGVGKSNLLSRFTRNEFNLDSKATIGVEFATRTIEIDGKTVKAQIWDTAGQERYRAITSAYYRGAVGALLVYDITKRQSFDNVSRWLEELREHADPNIVIMLVGNKSDLGHLREVPTEDAKEFAEEEGLFFMETSALEATNVEEAFETLLTEIY()}*

$19=164(164):
>Rab11  {11(0)|}consensus seq for RAB11/Rab22Gold.cma
{()YLFKVVLIGDSGVGKSNLLSRFTRNEFSLESKSTIGVEFATRSLQVDGKTIKAQIWDTAGQERYRAITSAYYRGAVGALLVYDVTKHVTFENVERWLKELRDHADSNIVIMLVGNKSDLRHLRAVSTEDAKAFAEREGLSFMETSALEATNVENAFQEILTEIY()}*

$20=164(164):
>Rab14  {|9(0)|}consensus seq for RAB14/Rab14Gold.cma
{()YIFKYIIIGDMGVGKSCLLHQFTEKKFMADCPHTIGVEFGTRIVEVSGQKIKLQIWDTAGQERFRAVTRSYYRGAAGALMVYDITRRSTYNHLSSWLTDARNLTNPNTVIFLIGNKSDLEAQRDVTYEEAKQFADENGLLFLEASAKTGDNVEEAFLETAKKIY()}*

$21=164(164):
>Rab18 consensus seq for RAB18/Rab18Gold.cma
{()TTLKILIIGESGVGKSSLLLRFVDDTFDPELAATIGVDFKVKTMTVDGNKVKLAIWDTAGQERFRTLTPSYYRGAQGVILVYDVTSRDSFVKLEHWLNELDTYStNNNIVKMLVGNKIDKE-NREVDREEGLKFARKHRMLFIEASAKTRDGVQCAFEELVEKII()}*

$22=164(164):
>Rab1  {|9(0)|}consensus seq for RAB1/Rab1Gold.cma
{()YLFKLLLIGDSGVGKSCLLLRFADDSYLESYISTIGVDFKIRTVEQDGKTIKLQIWDTAGQERFRTITSSYYRGAHGIIIVYDVTDQESFNNVKQWLNEIDRYASENVNKLLVGNKCDLTANKVVSYETAKAFADEIGIPFLETSAKNATNVEQAFMTMAAEIK()}*

$23=164(164):
>Rab1Like  {|9(0)|}consensus seq for RAB1/Rab1LikeGold.cma
{()YLFKLLLIGDSGVGKSCLLLRFSDDSFTTSFITTIGIDFKIRTIELDGKRIKLQIWDTAGQERFRTITTAYYRGAMGILLVYDVTDESSFNNIRNWIRNIEQHASDNVNKILVGNKADMDEKRAVPTEKGQALADEYGIKFFETSAKTNLNVEEAFFSLARDIK()}*

$24=175(164):
>Rab27  consensus
{()YLIKFLALGDSGVGKTSFLYQYTDNKFNSKFITTVGIDFREKRVVYRangpdgasgrGQRVHLQLWDTAGQERFRSLTTAFFRDAMGFLLLFDLTNEQSFLNVRNWMSQLQAHAyCENPDIVLCGNKADLEDQREVNEEQARELAEKYGIPYFETSAATGQNVEKAVETLLDLIM()}*

$25=164(164):
>Rab2  {|4(0)|} consensus seq for RAB2/Rab2Gold.cma
{()YLFKYIIIGDTGVGKSCLLLQFTDKRFQPVHDLTIGVEFGARMITIDGKPIKLQIWDTAGQESFRSITRSYYRGAAGALLVYDITRRETFNHLASWLEDARQHANANMTIMLIGNKCDLAHRRAVSKEEGEQFAKEHGLIFMEASAKTAQNVEEAFIKTAKKIL()}*

$26=164(164):
>Rab39 consensus seq
{()YLFKVILIGDSGVGKTSLLLRFTEGTFSEEYDSTIGVDFKSKTIEVDGKTIKLQIWDTAGQERFRSITRSYYRGAHGALLVYDVTNRESFESLDQWLEEIKEYASPNIPIILVGNKSDLEDKRQVSTEEAEAFAEQNGILFFETSAKTGENVEEAFETLARKIL()}*

$27=164(164):
>Rab3A  {|3(3)|}consensus seq for RAB3A/Rab3aGold.cma
{()YMFKLLIIGNSSVGKTSFLFRYADDSFTPAFVSTVGIDFKVKTVYRNDKRIKLQIWDTAGQERYRTITTAYYRGAMGFILMYDITNEESFNAVQDWATQIKTYSWDNAQVILVGNKCDMEDERVVSTERGRQLADQLGFEFFEASAKDNINVKQVFERLVDIIC()}*

$28=164(164):
>Rab4  {|6(0)|}consensus seq for RAB4/Rab4Gold.cma
{()YLFKYIIIGDTGVGKSCLLLQFTEKRFKPDHDHTIGVEFGTRMINVGGKSIKLQIWDTAGQERFRSITRSYYRGAAGALLVYDITRRETFNHLTTWLEDARQLASPNMVIILIGNKKDLEHRREVTYEEGSQFAKENGLIFLETSAKTGENVEEAFLQTAKKIL()}*

$29=164(164):
>Rab5 consensus seq for RAB5/Rab5Gold.cma
{()LQAKLVLLGDSGVGKSSLVLRFVKGQFDEFQESTIGAAFLSQTLALNDTTVKFEIWDTAGQERYHSLAPMYYRGAAAAIVVYDITNPDSFTRAKKWVKELQRQGNPNIVMALAGNKADLEDKRKVPAEEAQAYAEENGLFFMETSAKTADNVNDLFYEIAKKLP()}*

$30=164(164):
>Rab8  consensus
{()YLIKLLLIGDSGVGKSCLLLRFSDDSFTTSFITTIGIDFKIRTIELDGKRIKLQIWDTAGQERFRTITTAYYRGAMGILLVYDVTDEKSFNNIRNWIRNIEQHASENVNKILIGNKCDMDEKRAVSTEQGQALADEYGIKFFETSAKTNINVEEAFFSIARDIK()}*

$31=171(164):
>rabE  consensus
{()HLYKVLVIGDLGVGKTSIIKRYVHQFFSQHYRATIGVDFALKVLNWDENTlVRLQLWDIAGQERFGNMTRVYYKEAVGAFIVFDVTRPSTFEAVLKWKNDLDSKvtlpNGSPIPCVLLANKCDLEKEGIVnDSAQMDEFCKENGfIGWFETSAKENINIDEAARFLVEKIL()}*

$32=170(164):
>Rasef consensus seq
{()KAYKIVLAGDAAVGKSSFLMRLCKNEFRGNTSATLGVDFQMKTLIVDGERTVLQLWDTAGQERFRSIAKSYFRKADGVLLLYDVTCEKSFLNVREWVDMIEDAAHETIPIMLVGNKADL---RdtaaaegqkCVPGHFGEKLAMTYGALFCETSAKDGSNIVEAVLHLAREVK()}*

$33=164(164):
>RabFamB consensus seq
{()LEFKVVLLGDSGVGKTSLVLRFVKGTFDENYEATIGAAFLTKTVTVDDRTVKLQIWDTAGQERYRSLAPMYYRGADAAIVVYDITNRESFERAKSWVKELRKQAGPNIVIVLVGNKIDLEDKRQVSTEEAQEYAEENGALFFETSAKTGENVDELFEEIAKKLP()}*

$34=164(164):
>Rab21 consensus seq for RAB21/Rab21Gold.cma
{()NNFKVVLLGEGCVGKTSLVLRYVENKFNDKHISTLQASFLNKKLNIDGKRVNLSIWDTAGQERFHALGPIYYRDSNGAILVYDITDEDSFQKVKNWVKELRKMLGNDICLCIVGNKIDLEKQRKVSEAEAEEYAESVGAKHYHTSAKLNKGIEELFLDLTKRML()}*

$35=167(164):
>Rab34  {|3(4)|}consensus seq for RAB34/Rab34Gold.cma
{()KISKVIVVGDLSVGKTCLINRFCKDTFDKNYKATIGVDFEMERFEVLGVPFSLQLWDTAGQERFKCIASTYYRGAQAIIIVFDLNDVASLEHTKQWLEDaLKENDPSSVLLFLVGTKKDLSTPAQYSlmEKDALKVAQEMKAEYWAVSSLTGENVREFFFRVAALTF()}*

$36=164(164):
>Rab6 consensus seq for RAB6/Rab6Gold.cma
{()RKFKLVFLGEQSVGKTSLITRFMYDSFDNTYQATIGIDFLSKTMYLEDRTVRLQLWDTAGQERFRSLIPSYIRDSSVAVVVYDITNRNSFQQTSKWIDDVRTERGSDVIIMLVGNKTDLADKRQVSTEEGERKAKELNVMFIETSAKAGYNVKQLFRKIAAALP()}*

$37=168(164):
>Rab7 consensus seq for RAB7/Rab7Gold.cma
{()VLLKVIILGDSGVGKTSLMNQYVNKKFSNQYKATIGADFLTKEVMVDDRLVTMQIWDTAGQERFQSLGVAFYRGADCCVLVYDVTNPKSFKSLDSWRDEFLIQASPrdpeNFPFVVLGNKVDLEN-RAVSTKRAQAWCQSKGNiPYFETSAKEAINVEQAFQTIARNAL()}*

$38=164(164):
>Rablike consensus seq for RAB_LIKE/RabLikeGold.cma
{()YLFKLVLLGDSGVGKTSLLLRFVDDSFTNSYESTIGADFLTKTVELDDKTVKLQIWDTAGQERFRSLTPAYYRGADGAIVVYDITNEESFNNLKSWVDEIRRQASPNVVIVLVGNKCDLEDKRVVSTEEAQAYADELGIPFFETSAKEAINVEQAFRTIARKLP()}*

$39=164(164):
>Ypt52 consensus seq
{()LQFKLVLLGDSGVGKSSLVLRFVKGQFDEYQESTIGAAFLTQTVSLDDTTVKFEIWDTAGQERYHSLAPMYYRGAAAAIVVYDITSPDSFEKAKSWVKELQRQGNPNIVIALVGNKADLEEKREVSTEEAEAYAEENGLLFFETSAKTGENVNELFTEIAKKLP()}*

$40=176(164):
>Cdc42pRac1 consensus seq for CDC42_RAC1/Cdc42Rac1Gold.cma
{()QTIKCVVVGDGAVGKTCLLISYTTNAFPGEYVPTV-FDNYSANVMVDGKPYNLGLWDTAGQEDYDRLRPLSYPQTDVFLICFSVVSPASFENVKeKWYPEISHHC-PNTPIILVGTKLDL---RddpetieklaekklsPITYEQGLKLAKEIGaVKYLECSALTQKGLKNVFDEAIRAVL()}*

$41=168(164):
>HypoF consensus
{()EVVTILLLGDAGCGKSTFLSRLKAGEARNNINTSIPLLRdsdqpFIFDIRFSKKSFRLEFYDTASPQHWSTLQP------DVVVLCFDISNRLSLINLKRWRNEIIRYFQRgdGLPVMVLGLKRDL---RsegdgIIYPQEGYRIAQELRcDRYAECSAVTGELLAETFEDLARTAG()}*

$42=176(164):
>RhoA consensus seq for RHOA/RhoAGold.cma
{()IRKKLVIVGDGACGKTCLLIVFSKDQFPEVYVPTV-FENYVADIEVDGKQVELALWDTAGQEDYDRLRPLSYPDTDVILMCFSIDSPDSLENIPeKWTPEVKHFC-PNVPIILVGNKKDL---RndektirelakmkqePVKPEEGRAMADKINaYGYLECSAKTKEGVREVFETATRAAL()}*

$43=176(164):
>RhoF consensus seq for RHOF/RhoFGold.cma
{()KEVKIVIVGDGGCGKTSLLMVYAKGSFPEKYAPSV-FEKYTTSVTIGGKEVTLNLYDTAGQEDYDRLRPLSYQNTNLVLICYDVTNPTSYDNVLiKWYPEVNHFCR-GVPIVLIGCKTDL---RkdkeqlrklrasqqePITYNQGEAACKQINaEIYLECSAKYRENVENVFREATKIAL()}*

$44=176(164):
>RhoLike consensus seq for RHO_LIKE/RhoAGold.cma; 
{()QEIKLVVVGDGAVGKTCLLISYTTNAFPEEYVPTV-FDNYSANVMVDGKPVNLGLWDTAGQEDYDRLRPLSYPQTDVFLICFSVDSPDSFENVKeKWIPEVKHFC-PNVPIILVGTKLDL---RndehtrrelakmkqePVTYEQGEALAKKIGaVKYLECSALTQEGVKEVFDEAIRAVL()}*

$45=161(164):
>RhoT1 consensus seq for RHOT1/RhoT1Gold.cma
{()KDVRIVLVGDPGVGKTSLIMSLVSEEFPEA-VPRR-AEEITIPADVTPERVPTSIVDTSSAEES-DAAAAEIRQANVICIVYSVDCESTLDGITRWLPLIRSLEDSRAPVILVGNKSDL---RdysLEDTILPIMEAYTEVETCVECSAKTLKNVSEVFYYAQKAVL()}*

$46=176(164):
>Rnd consensus
{()VRRKLVVVGDGACGKTSLLIVFAKGYFPEVYVPTV-FENYVADIEVDGKRVELALWDTAGQEEYDRLRPLSYPDSDVILICFSIDSPDSLDNVLkKWIPEVLHFC-PGVPIILVGCKSDL---RtdpstieelskqgqtPVTYEQGLAVAKQIGaVKYLECSAKTGEGVREVFEAATRAAL()}*

$47=174(164):
>Rop  {|4(0)|} consensus seq
{()RFIKCVTVGDGAVGKTCMLISYTSNTFPTDYVPTV-FDNFSANVVVDGSTVNLGLWDTAGQEDYNRLRPLSYRGADVFVLAFSLISRASYENVSkKWIPELRHYAP-GVPIVLVGTKLDL---RedkqyladhpgavPITTAQGEELRKQIGaAAYIECSSKTQQNVKAVFDAAIKVVL()}*

$48=161(164):
>RanLike consensus seq for RANLIKE/RanLikeGold.cma
{()AEFKLVLVGDGGTGKTTFVKRHLTGEFEKKYIATLGVEVHPLQFYTNFGTICFNVWDTAGQEKFGGLRDGYYIQGQCGIIMFDVTSRITYKNVPNWHRDLERVC-ENIPIVLCGNKVDVKD-RKVKTGQV-TFHRKKNLQYFEISAKSNYNFEKPFLWLARKLV()}*

$49=161(164):
>RanPlant  {|11(0)|}consensus seq for RANPLANT/RanPlantGold.cma
{()PSFKLVIVGDGGTGKTTFVKRHLTGEFEKKYEPTIGVEVHPLDFFTNCGKIRFYCWDTAGQEKFGGLRDGYYIHGQCAIIMFDVTSRLTYKNVPTWHRDLCRVC-ENIPIVLCGNKVDVKN-RQVKAKQV-TFHRKKNLQYYEISAKSNYNFEKPFLYLARKLT()}*

$50=161(164):
>Ran  {|8(0)|}consensus seq for RAN/RanGold.cma
{()PTFKLVLVGDGGTGKTTFVKRHLTGEFEKKYVATLGVEVHPLKFHTNRGPIRFNVWDTAGQEKFGGLRDGYYIQGQCAIIMFDVTSRVTYKNVPNWHRDLVRVC-ENIPIVLCGNKVDVKD-RKVKAKTI-TFHRKKNLQYYDISAKSNYNFEKPFLWLARKLV()}*

$51=191(164):
>OddFY consensus seq for 
{()YNMKIVIRGDRNTGKTALWHRLQGKKFVEEYIPTQEIQVTSIHWNYKTTDdvVKVEVWDVVDKGkckkrgdglkmendpqeAESEMALDAefldvYKNCNGVVMMFDITKQWTFNYVLRELPKVPTH----VPVCVLGNYRDMGEHRVILPDDVRDFIDSLDRPpgssyfrYAESSMKNSFGLKYLHKFFNIPFL()}*

$52=191(164):
>Parf consensus
{()YNMKIVIRGDRNTGKTALWHRLQGKKFVEEYIPTQEIQVTSIHWNYKTTDdvVKVEVWDVVDKGkckkrgdglklendpqeAESEMALDAefldvYKNCNGVVMMFDITKQWTFNYVLRELPKVPTH----VPVCVLGNYRDMGEHRVILPDDVRDFIDNLDRPpgssyfrYAESSMKNSFGLKYLHKFFNIPFL()}*

$53=158(164):
>Hydra consensus
{()KPIRIVVLGQCGVGKTALVSRCLTNQFFN--DSSSGKDIaYRYNMTINKKKSVLDIVDFNGKND------ALISCADAFILVYSITDRKSFEAIDALLDKVRELNIKSPKIGVVGNKIDLYKDREVSSTEGLELAKEINSLFYETSAKvPVIDVRQIFYDLYQSLK()}*

$54=171(164):
>eMiro consensus
{()ASYKIFVSGKSGVGKTALVAKLAGLEVPVVHHETTGIQttvvFWPAKLQASDRVVmfRFEFWDCGESalKKFDHILPACKEKADAFLFLFSFTDRASFEDLPGQLSRVAGEA-PGVVRMVIGTKFDQYMHTDVTERDLTAFRQAWELPLLRVKSVPGRRLADGRTLDGRAGL()}*

$55=237(164):
>Grlf consensus seq for GRLF/GrlfGold.cma
{()PTYNISVVGLSgtekekgqcGVGKSCLCNRFVRPSAdeYHLDHTSVLstsdfggrvvnNDHFLYWGEVSrsledGVECKIHVVEQTEFIDdqtfqphrstnlqpyikraaatklqsaeklmyictdqlgleqdfEQKQMPDGKLNVDGFLLCIDVSRGmnRNFDDQLKFVSNLyNQLAKTKKPIVIVLTKCDEGVERYIRDAHTFALSKK-NLQVVETSARSNVNVDLAFTTLVQLID()}*

$56=171(164):
>kappaB_Ras consensus seq for KAPPA_B_RAS/kB_RasGold.cma
{()KICKVVVCGGKGVGKTAIIEQLIYGNHTTGTPdcPTI-EDTYSASVETDRGGakEKLRIYDTGGlQEGQSELPKHYFSFADAFVLVYDIADSESFQRVDLLKKDIDKYKDKKeVPIVVLGNKRDRPAGRTVDSVMARAssWAQREKVKLFEVTVSDRQSLIDPFTWLCSRIT()}*

$57=179(164):
>MglA consensus seq for MGLA/MglAGold.cma
{()EINcKIVYYGPGLSGKTTNLQHIYQKTAPEakgkmislatETDRTLFFDFLPLALgEVRGFKTRFHLYTVPGQVFYDASRKLVLKGVDGVVFVAD-SQPERMDANIESLENLREnlaeqgYDLDKIPLVIQYNKRDLPNALPVEELRRE--LNPTGVPVFEAVALTGEGVFETLKAVAKLVL()}*

$58=161(164):
>Miro  {|4(15)|}consensus
{()RRKSVVLLGVGGVGKTTYIYRLLGLSLRPRVTLRPGI------YRLYLGDKEIDLVDVPGQyatevaRNFARAWTFY---VDLAIYMYDVTDQETLYALAEIHSALLDRGIKpYKRVVLVGNKRDLAEELGVFVEGDEIATALGASEVYYISALK-DPPEVLYKILLENLP()}*

$59=161(164):
>Pike consensus seq for PIKE_CENTAURIN/PikeGold.cma
{()PELKLGIVGNLASGKSALVHRYLTGTYV-QEESTEGGRFK-KEIVVDGQSHLLLIRDEGGPPDA-----QFAGWVDAVIFVFSLEDEISFQTVYHLYSRMASYRNtSEIPLVLVGTQ-DAIsasNPRVIDDARARKLSADLKRcSYYETCATYGLNVERVFQDVAQKIV()}*

$60=163(164):
>plantFY consensus
{()KRPGVLVVGSSGVGKRTLLSRLLSVDF-EDSDSSSEVLVHGWTINTKYYTADVSVWMAHLCD--SITSLPMSDQLVALVMVFDLNNLSSLVALQDWVSHADIQKFD--ILLCIGNKVDLVPGHEEPSLDIRrsclEWCLEHNIEYIEACASNPDFDKCLSVDGDSQGV()}*

$61=169(164):
>RayL consensus
{()LRAKCIVVGDATVGKSALIQMFHSDgaHFPKNYTMTTGVDLVVKPVVIPDTNdsVELYIFDSAGKELFSEMLSKYWEGPSVVILVYDVTNEESFESCKKWLERVKsQKPGRELPGVLVANKTDLAGRRAVDPKQAQDWARGNGLEFFECSAKEMENVDAPFNYLANEFY()}*

$62=164(164):
>Rsl11A consensus seq
{()KEVKIAVLGDGGVGKSALTVRFLTKRFIGEYDPTIGEDSYSKTVTVDGEQVSLEILDTAGQEEYRGMRESYIRWADGFLLVYSITDRSSFEAAKPLLERIREHAKRNVPVILVGNKCDLEHARQVSTEEGEELARELGCLFMETSARENVNVEEAFQELCREVL()}*

$63=169(164):
>Sid3 consensus seq for SID3_TEM1/Sid3Gold.cma
{()VVVKVGMVGDSQIGKTSLMVKYVEGSFDEDYIQTlVGVNFMEKTISIRNTEITFSIWDLGGQREFVNMLPLVCNDAVAILFMFDLSRKSTLNSIKEWYRQARGFNKTAIPF-LVGTKYDHFATFPReeqeeITKQARRFAKAMKAPLVFCSTSHSINVQKIFKVVLAKVF()}*

$64=164(164):
>RhoT2 consensus seq for RHOT2/RhoT2Gold.cma
{()NVFQCNVIGAKGAGKTAFLQAFLGRRMAAAAGRRHSNRYAINTVEVYGQEKYLVLRDVGSRDVATGLGNTELAACDVACFVYDSSNPKSFEYCARIRDQQKYFAGSKIPCLIVATKADLDEVDQEYEVSPTDFCRKGKLLKPQGFGTGDANNKISCGISTALAM()}*

$65=205(164):
>ExRas1 consensus
{()DKVRVIVVGDSGVGKTSLTHLIAHNEPLTSPGWTVGCSVEVKLHEYKEgtpaqKTFFVELWDVGGSISHKNTRGVFYNPTHGIILVHDLTNRKSHQNLQKWLAEILNKDGKDalkggdfddfdpeqflgstqIPILVIGTKLDLLDEVRKNKIRRSAGsiaeqcgadeiclnchEARSLAAGTTDAVKLSRFFDKVIERKYYSRD()}*

$66=211(164):
>PlantExRas2 consensus
{()GQVRVLVVGDSGVGKTSLVHLIVKGSSIARPPQTIGCTVGVKHFTYGSpgsssNSIKgdaerdffVELWDVSGHERYKDCRSLFYSQINGVIFVHDLSQRRTKTSLQKWAAEIAATgtfsaplgsggpGGLPVPYLVIGNKADIAAKEGTrgssgnLVDVARQWVEKQGLLpsseelpltesfpgsgGLLAAAKEARYDKEAVMKFFRMLI()}*

$67=164(164):
>T2_ArlGa consensus seq
{()KEVKILLLGLDNAGKTTILKQLKIGEVLVTTVPTIGFNVETFTVSLGYKNIKFRVWDVGGQRSERPKWRHYFENVTAIIFVVDSSDRDRLEESKEELHSILNEELRGAPLLVFANKQDLPGAKSPAEISELLGLKDRKWYIQFTSATDGEGLDEGFDWLVDTIK()}*

$68=163(164):
>Arf1 consensus seq for ARF1/Arf1Gold.cma
{()KEMRILMVGLDAAGKTTILYKLKLGEI-VTTIPTIGFNVETVE----YKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDRERVGEAREELMRMLNEdELRDAVLLVFANKQDLPNAMNAAEITDKLGLhslRNRNWYIQATCATSGDGLYEGLDWLSNQLK()}*

$69=163(164):
>Arf3 consensus seq for ARF3/Arf3Gold.cma
{()KEIRILMLGLDAAGKTTILYKLKLGEV-VTTIPTIGFNVETVE----YKNLSFTVWDVGGQDKIRPLWRHYYQNTQALIFVVDSNDRERIDEAKEELHKMLSEdELRDAALLVFANKQDLPGAMSAAEISEKLGlgeLRDRKWHIQACSATTGEGLYEGLDWLSNNLK()}*

$70=163(164):
>Arf6 consensus seq
{()KEMRILMLGLDAAGKTTILYKLKLGQS-VTTIPTVGFNVETVT----YKNVKFNVWDVGGQDKIRPLWRHYYTGTQGLIFVVDCADRDRIDEARQELHRIINDrEMRDAIILIFANKQDLPDAMKPHEIQEKLGLtriRDRNWYVQPSCATTGDGLYEGLTWLTSNYK()}*

$71=163(164):
>Arf_like consensus seq for ARF_LIKE/ArfLikeGold.cma
{()KEMRILILGLDNAGKTTILYKLKLGEV-VTTIPTIGFNVETVE----YKNLKFNVWDVGGQESLRPYWRHYYENTDALIFVVDSTDRERLEEAKEELHKLLQEeELKGAPLLVFANKQDLPGALSAAEISEALGLhslKKRKWHIQPCSALTGEGLKEGLDWLVNQLK()}*

$72=173(164):
>ArfRP consensus seq for ARFRP/ArfRPGold.cma
{()DEYCILILGLDNAGKTTYLEQAKT-KFtknykgmnPSKITTTVGLNIGTID----IGGVRLNFWDLGGQEELQSLWDKYYAESHAVIYVIDSSDRERLSESKEAFDKMISSeALSGVPLLVLANKQDVPDCMGVREIKPVFsdsahLIGRRDCLVMPVSALTGEGVDEGIEWLVECVK()}*

$73=164(164):
>Arl10 cons seq for ARL10/Arl10Gold.cma
{()QEMELSLVGLQNAGKTSLVNVIATGGYSEDMIPTVGFNMRKVT----KGNVTIKLWDLGGQPRFRSMWERYCRGVSAIVYVVDAADRDNLSISRSELHDLLSKpSLSGIPLLVLGNKIDKPGALSKQALIDQMGlksITDREVCCYMISCKNSTNIDIVIDWLIKHSK()}*

$74=163(164):
>Arl1 consensus seq for ARL1/Arl1Gold.cma
{()KEVRILILGLDGAGKTTILYRLQVGEV-VTTIPTIGFNVETVT----YKNIKFQVWDLGGQTSIRPYWRCYYANTDAIIYVVDSADRDRIGISKQELVAMLEEeELRGAILLVFANKQDLPGALSPAEVSEALGlsaLKNRQWQIFKTSALKGEGLDEGMDWLVNTLK()}*

$75=164(164):
>Arl2 cons seq  for ARL2/Arl2Gold.cma
{()KEMRILMLGLDNAGKTTILKKL-NGEDISTISPTLGFNIKTLE----YQGFKLNIWDVGGQKTIRSYWRNYFENTDGLIWVVDSSDRRRLDDCGEELHELLKEeRLSGAPLLIFANKQDLPGALSPSEIAEVLNldsiDRDRHWQIQGCSAVTGEGLLEGMDWLVKDIA()}*

$76=223(164):
>Arl3fungal consensus seq for ARL3/Arl3FungalGold.cma
{()EEYSVLLLGLDNAGKTTLLEQIKALYLprpdgapapnPGKTVPTVGQNVATIP----LPDMYLKIWDVGGQISMRNLWQSYYSSCHAIIFVVDSTDVGqdpdisrlpsnrkpssasgpsaggsdafteelaginapgsefgRLDECRQVLESVLQHsDVEGVPILVLANKQDREDCVEVVRIKEGFVrkvFEGeegggvRDSRVLPVSALMGTGVREAVEWVQSRVK()}*

$77=163(164):
>Arl3 consensus
{()QEVRILLLGLDNAGKTTILKQL-ASEDITHITPTQGFNIKSVQ----SQGFKLNVWDIGGQRKIRPYWRNYFENTDVLIYVIDSADRKRFEETGQELAELLEEeKLKGVPVLIFANKQDLLTAAPASEIAEGLNlhtIRDRTWQIQACSALTGEGVQDGMNWVCKNVK()}*

$78=169(164):
>Arl4 consensus seq for ARL4/Arl4Gold.cma 
{()QSLHIVMLGLDSAGKTTVLYRLKFNEF-VNTVPTIGFNTEKIKVSLGTaKGITFHFWDVGGQEKLRPLWKSYTRCTDGIVFVVDSVDVERMEEAKTELHKITKFsENQGVPVLVLANKQDLPGALSVAEIEKLLAlhelSPATPWHVQPACAIIGEGLQEGLEKLYEMIL()}*

$79=163(164):
>Arl5 consensus seq for ARL5/Arl5Gold.cma
{()KEYKIVVVGLDNAGKTTTLYKLHLGEV-VTTHPTIGSNVEELV----YKNIRFEVWDLGGQESLRTSWATYYRGTHAVIVVIDSTDRARISIMKDELFRLLQHeDLQNAVVLVFANKQDLKDAMTPAEITDALSlhsIKNHDWHIQACCALTGEGLYDGLGWIAQRVT()}*

$80=167(164):
>Arl6p consensus
{()KEVHVLCLGLDNSGKTTIINKLKpSNAQSQDIVPTIGFSIEKFK----SSSLSFTVFDMSGQGRYRNLWEHYYKEGQAIIFVIDSSDRLRMVVAKEELDTLLNHpDIkhRRIPILFFANKMDLRDAVTSVKVSQLLClenIKDKPWHICASDAIKGEGLQEGVDWLQDQIQ()}*

$81=164(164):
>Arl8 consensus
{()EEMELTLVGLQYSGKTTFVNVIASGQFSEDMIPTVGFNMRKVT----KGNVTIKVWDIGGQPRFRSMWERYCRGVNAIVYMVDAADHEKLEASRNELHNLLDKpQLAGIPVLVLGNKRDLPGALDEKELIERMNlsaIQDREICCYSISCKEKDNIDITLQWLIQHSK()}*

$82=163(164):
>Plant1Arl consensus seq for PLANT1_ARL/Plant1ArlGold.cma
{()KEMRVVMLGLDAAGKTTILYKLHIGEV-LSTVPTIGFNVEKVQ----YKNVMFTVWDVGGQEKLRPLWRHYFNNTDGLIYVVDSLDRERIGKAKAEFQAIINDpFMLNSVILVFANKQDMKGAMTPMEVCEGLGlydLKNRKWHIQGTCALKGDGLYEGLDWLASTLK()}*

$83=163(164):
>Plant2Arl consensus seq for PLANT2_ARL/Plant2ArlGold.cma
{()KEARILVLGLDNAGKTTILYRLQMGEV-VSTIPTIGFNVETVQ----YNNIKFQVWDLGGQTSIRPYWRCYFPNTQAIIYVVDSSDTDRLVIAKEEFHAILEEeELKGAVVLIYANKQDLPGALDDAAVTEALElhkIKSRQWAIFKTSAIKGEGLFEGLDWLSNTLK()}*

$84=170(164):
>Plant4Arl consensus seq for PLANT4_ARL/Plant4ArlGold.cma
{()AEFHVLILGIDKAGKTTLLEKLKSIysnlegLPPDRIVPTVGLNIGRIE----VSNTKLVFWDLGGQPGLRSIWEKYYEEAHAVIYVIDAACPSRFEDSKSALEKVLRHeDLQGAPLLILANKQDLPGAVSAEELARYLDlkkLDERPYMFEAVSAYDGTGIKEGVDWLVEVME()}*

$85=175(164):
>Sar1 consensus seq for SAR/Sar1Gold.cma
{()KNGKLLFLGLDNAGKTTLLHMLKD-DRMAQHVPTLHPTSEELSI----GGIKFTTFDLGGHEQARRVWKDYFPAVDGIVFLVDAADRERFPESKAELDSLLSdEELANVPFLILGNKIDIPGAVSEDELRNALGLygqttgkgkvalddlPIRPIEVFMCSVVKRQGYGEGFRWLSQYID()}*

$86=311(164):
>Galpha consensus
{()REVKLLLLGAGESGKSTILKQMRIIHGngfseeerlefrpviylnivqsmktlldameelgipledpeneehadlilsldplreepltpeyaeaikalwadpgiqecyerrnefqlndsakyfldnldriaspdyvptdqdiLRARVRTTGIIETSFTV----KGITFRIVDVGGQRSERRKWIHCFDDVTAIIFVAALSEYDqvlvedestnRMEESLNLFESICNSKwFANTSIILFLNKIDLFEEKIKKSplkkyfpeytgdndyeaaskfikekFLSLNRNPSKEIYTHFTCATDTENIKFVFDAVKDTIL()}*

$87=316(164):
>Ga12 consensus
{()RLVKILLLGAGESGKSTFLKQMRIIHGrefdqkallefrdtifdnilkgsrvlvdardklgipwqysenekhgmflmafenkaglpvepatfqlyvpalsalwrdsgireafsrrsefqlgesvkyfldnldrigqlnyfpskqdiLLARKATKGIVEHDFVI----KKIPFKMVDVGGQRSQRQKWFQCFDGITSILFMVSSSEYDqvlmedrrtnRLVESMNIFETIVNNKlFFNVSIILFLNKMDLLVEKVKTVsikkhfpdfrgdphrledvqrylvqcFDRKRRNRSKPLFHHFTTAIDTENVRFVFHAVKDTIL()}*

$88=317(164):
>GaDiverse  consensus
{()KEVKLLLLGAGESGKSTILKQMKILYAngfseeeraewrpviylnivesiktllealerfnielespesedeaslesikyelspnafedqlppelaedikelwndpsiqelyerrnefylpdsagyfldnidriaspdyvptdqdiLRARVRTTGISETRFDL----DGLKFRLFDVGGQRSERKKWIHCFDDVTAIIFVVSLSEYDqvleedksvnRLEESLLLFESIVNSPlFAKTPLILFLNKIDLFKEKLKGVplskyfpdygggpndyesaakyirdkfKELNRANSPNKIYPHFTSATDTSNIKLVFASVRDTIK()}*

$89=311(164):
>GaITO consensus
{()REVKLLLLGAGESGKSTIVKQMKIIHEdgyseeeckqykpvvysntiqsmiaiiramgtlkidfgdparaddarqlfdlagsegvltpelagaikrlwkdsgvqacfnrsreyqlndsaayylndldriaapdyipteqdvLRTRVKTTGIVETHFTF----KDLHFRMFDVGGQRSERKKWIHCFEGVTAIIFCVALSEYDqvlaedeetnRMHESLKLFDSICNNKwFTDTSIILFLNKKDLFEEKIKKSplticfpeytggntyeeaaayiqaqfEDLNKRKDTKEIYTHFTCATDTNNIQFVFDAVTDVII()}*

$90=313(164):
>Ga consensus seq for G_ALPHA/GaGold.cma; (aln structurally OK)
{()REVKLLLLGAGESGKSTIVKQMKIIHGggyneeekrsykpiiysntvqsmrvilrameelkipfedannendaaaqimrlvasdedsdlppelaeaikalwadkgvqecfsrsreyqlndsakyyldsidriaqpdylpteqdvLRSRVKTTGIVETKFTI----DKLTFRMFDVGGQRSERKKWIHCFEDVTAIIFVVALSEYDqvlyedestnRMQESLTLFDSICNNRwFTNTSIILFLNKKDLFEEKIPKSpltdyfpeyagnrdyeeaseyildrFVSLNKAGRKQIYTHFTCATDTENIRFVFNAVKDIIL()}*

$91=337(164):
>PlantGa1  consensus
{()HIQKLLLLGAGESGKSTIFKQIKLLFQtgfdeaelksyipvihanvyqtikilhdgskelaqneldsskyvispenkeigeklseiggrldyphltkelvqdietlwkdpaiqetyargnelqvpdcahyfmenlqrlsdanyvptkedvLYARVRTTGVVEIQFSP----VGENkksgevYRLFDVGGQRNERRKWIHLFEGVTAVIFCAAISEYDqtlfedenknRMMETKELFEWVLKQPcFEKTSFMLFLNKFDIFEKKILKVplnvcewfkdyqpvstgkqeiehayefvkkkfEELYFQSTApdrvdRVFKIYRTTALDQKLVKKTFKLVDETLR()}*

$92=383(164):
>PlantGa consensus
{()RIQKLLLLGSSGSGTSTIFKQAKFLYGtrftqeeleniklmiqsnmykylgillegrerfeeealagsnctssedentqadenkangsdsciysinprlkkfsdwlldiiamgdldaffpaatreyapiveemwkdpaiqatykrkdelhflpdvaeyflsraievssneyepsekdiIYAEGVTQGNGLAFIEFSLDDRSpmsesytdnpeahsqplTKYQLIRVNAKgMNEGCKWVEMFEDVRMVIFCVSLSDYDqvgpsssgtsplqnKMIQSKELFEATIRHPcFEDTPFVLILNKYDLFEEKINRVplttcewfsdfcpvrthhnnqslaqqayyyvamkfKDLYASLTGRKLFVWQARARDRATVDEAFKYIREVLK()}*

$93=312(164):
>GaQ consensus
{()RELKLLLLGTGESGKSTFIKQMRIIHGsgysdedkrgftklvyqniftamqamiramdtlkipykdeqnkehaqlirevdvekvttfenpyveaikslwndpgiqecydrrreyqlsdsakyylsdldriaapdylptqqdiLRVRVPTTGIIEYPFDL----ESIIFRMVDVGGQRSERRKWIHCFENVTSIIFLVALSEYDqvlvesdnenRMEESKALFRTIITYPwFQNSSVILFLNKKDLLEEKIMYShlvdyfpeydgpqrdaqaarefilkmFVDLNPDSDKIIYSHFTCATDTENIRFVFAAVKDTIL()}*

$94=331(164):
>GaS consensus
{()ATHRLLLLGAGESGKSTIVKQMRILHVngfngeekktkiqdiknnlkeaietivaamsnlvppvelanpenqfrvdyilsvanvpdfdfppefyehakalwedegvracyersneyqlidcaqyfldkidvikqadytpsdqdlLRCRVLTSGIFETKFQV----DKVNFHMFDVGGQRDERRKWIQCFNDVTAIIFVVASSSYNmvirednqtnRLQEALNLFKSIWNNRwLRTISVILFLNKQDLLAEKVLAGkskiedyfpefaryttpedatpepgedprvtrakyfirdeflrISTASGDGRHYCYPHFTCAVDTENIRRVFNDCRDIIQ()}*

$95=164(164):
>T3_EF_like consensus seq
{()RIRNIGVIGHVDHGKTTLTGALLYKTGGIDRGITIDSAATKFETEXXXXKYRINIIDTPGHVDFSKNMIRGLSQADGAVLVVDAVEGVEPQTREHLLLARTLKTAGGVKIIVFINKMDRVGADEIKEEVEKALKKPEDVPFIPGSALTGDGIDELSEAIVWYKG()}*

$96=205(164):
>EF1Alike  consensus
{()QHLNLVVIGHVDAGKSTLMGHLLYLLGGVSeremhkleqeakklgkssfayawvldetkeereRGVTIDVGTKEFETE----TKHYTLIDAPGHKDFIPNMISGAAQADVALLVVDAS-GEfeagfekGGQTREHALLVRSL----GVKqLIVAVNKMDQVGwsqerFDEIKGELKHFLKQagfkESDVPFIPISGLSGENLIKKSELMKWYKG()}*

$97=201(164):
>CysNC consensus seq for CYSNC/CysNC_Gold.cma
{()SLLRFLTCGSVDDGKSTLIGRLLHDSKQIYedqlaalerdskkrgttgekldlallvdglqaereQGITIDVAYRYFSTE----KRKFIIADTPGHEQYTRNMATGASTADLAIILIDARKGVLTQTRRHSFIASLL----GIKhVVVAVNKMDLVDYSEEVFEEIRadylAFAEQLGltptdIRFIPLSALKGDNVVSRSENMPWYSG()}*

$98=199(164):
>EF1A_archaea consensus
{()PHLNLVFIGHVDHGKSTTVGRLLLDSGAIDehtiekyekeaeekgkagfkfawvmdglkeereRGVTIDVAHKKFETP----KYYFTIIDAPGHRDFVKNMITGASQADAAVLVVAANDGVNGQTKEHAFLARTL----GVKqLIVAVNKMDIVGysedrYNEVKEEVSKLLKMagfkPDDIPFIPVSALKGDNVVKKSDNMPWYNG()}*

$99=208(164):
>EF1a consensus  seq for EF1A/EF1aGold.cma
{()THINIVVIGHVDSGKSTTTGHLIYKCGGIDkrtiekfekeaaemgkgsfkyawvldklkaereRGITIDIALWKFETP----KYYVTIIDAPGHRDFIKNMITGTSQADCAVLIVAAGTGEfeagiskNGQTREHALLAFTL----GVKqLIVGVNKMDSTEppysearFEEIVKEVSSYIKKigynPKAVPFVPISGWHGDNMLEPSTNMPWYKG()}*

$100=208(164):
>EF1A_mfp consensus
{()THINIVVIGHVDSGKSTTTGHLIYKCGGIDkrtiekfekeaaemgkgsfkyawvldklkaereRGITIDIALWKFETP----KYYVTIIDAPGHRDFIKNMITGTSQADCAVLIVAAGTGEfeagiskNGQTREHALLAFTL----GVKqLIVAVNKMDSTEppysearYEEIVKEVSNYIKKvgynPKAVAFVPISGWHGDNMLEPSTNMPWYKG()}*

$101=208(164):
>EF1A_plants consensus
{()VHINIVVIGHVDSGKSTTTGHLIYKLGGIDkrvierfekeaaemnkrsfkyawvldklkaereRGITIDIALWKFETT----KYYCTVIDAPGHRDFIKNMITGTSQADCAVLIIDSTTGGfeagiskDGQTREHALLAFTL----GVKqMICCCNKMDATTpkyskarYDEIVKEVSSYLKKvgynPDKIPFVPISGFEGDNMIERSTNLDWYKG()}*

$102=209(164):
>Erf consensus seq for ERF/ErfGold.cma
{()EHVNVVFIGHVDAGKSTIGGQILYLTGMVDkrtlekyereakeknretwylswaldtnqeerdKGKTVEVGRAYFETE----KKRFTILDAPGHKSFVPNMIGGASQADLAVLVISARKGEfetgFEKGGQTREHAMLAKTAGVKHLIVLINKMDDPTvnwskerYEECKEKLVPFLKKvgfnPKKdIHFMPCSGLTGANLKERVDFCPWYTG()}*

$103=165(164):
>bSelB  consensus
{()XXMIVGTAGHVDHGKTALVKALTGIDTDRLpeekrRGITIDLGFAYLDLG----GRRLGLVDVPGHERFIKNMLAGAGGIDLVLLVVAADEGVMPQTREHLAIIRLL----GIErGIVALTKADLVDAERLELVREEVRELlsfLEDAPIVPVSALTGEGIDELRAALAALAA()}*

$104=204(164):
>aEF2  {|10(53)|}consensus
{()QIRNIGIAAHIDHGKTTLSDNLLAGAGMISeelagkalaldfdeqeqaRGITINAANVSMVHEYEGKDYLINLIDTPGHVDFGGDVTRAMRAVDGAIVVVDAVEGVMPQTETVLRQALKE----KVRPVLFINKVDRLINELKLTPEEMQERFAKiikkvnkliktyapeefkkkwkvdvqDGTVAFGSAYYNWGISVPYMQKTGISF()}*

$105=213(164):
>eEF2 consensus
{()NIRNMSVIAHVDHGKSTLTDSLVSKAGIIAaakagearftdtrkdeqeRCITIKSTAISLYFELDdedlkfIKtdgnGFLINLIDSPGHVDFSSEVTAALRVTDGALVVVDCVSGVCVQTETVLRQALAE----RIKPVLFMNKMDRALLELQLEKEDLyqtFQRIVEnvnviiatyddgpmgdvqvdpsKGTVAFGSGLHGWAFTLKQFAEMYAKK()}*

$106=173(164):
>EF_like consensus seq
{()RIRNIGIIAHVDHGKTTLTDRILFYTGVIHkgevhgaavmdwmeqereRGITIKSAATTCEW-------RINIIDTPGHVDFTIEVERSLAVLDGAILVVDAVDGVEPQTEEVWRLAKEY----GVPIIVFVNKMDRPGADFeRVVEEVEQLILADDVPIIPASARKGTpLLDAVDYLPDIPLV()}*

$107=182(164):
>EFTu consensus  seq for EFTU/EFTuGold.cma
{()PHVNIGTIGHVDHGKTTLTAAITKVLAEKGgaeakaydqidkapeekeRGITINTAHVEYETE----NRHYAHVDCPGHADYVKNMITGAAQMDGAILVVSAADGPMPQTREHILLARQV----GVPaIVVFLNKVDMVDDEELLELVEMEVRELLssydfpgdDIPIIKGSALKALEGDDE-EIGKIAIL()}*

$108=214(164):
>eIF2 consensus seq for eIF2/eIF2Gold.cma
{()RSPICCVLGHVDTGKTKLLDKI-RGTNVQDgeaGGITQQIGATYVPLeaikeqtkmlkkfdREELKIPGLLIIDTPGHESFSNLRSRGSSLCDIAILVVDIMHGLEPQTIESINLLKSR----KTPFIVALNKIDRLYgwkkspnapfaetlkkqkknVQDEFEERLKEIIVEFAeqglnaelyyenkdfrktVSIVPTSAITGEGIPDLLLLLVGLTQ()}*

$109=191(164):
>EIF2G cons seq for EIF2G/EIF2G_Gold.cma
{()ATINIGTIGHVAHGKSTVVKAISGVQTVRFkneleRNITIKLGYANAKIYKcpkcpryrssppcpgcggrFELVRHVSFVDCPGHDILMATMLNGAAVMDAALLLIAANESCPQpQTSEHLAAIEIM----KLKhIIILQNKIDLVKEEqakeqyeQIKKFVK--GTVAEGAPIIPISAQLKYNIDVLCEYIVKKIP()}*

$110=171(164):
>SelB consensus seq for SELB/SelBGold.cma
{()VNVNVGVLGHIDSGKTALARALSTTASTAAfdkqpqsreRGITLDLGFSCFSEE----LLQVTLVDCPGHASLIRTIIGGAQIIDLMMLVIDVTKGMQTQTAECLVIGQI-----ACQkLVVVLNKIDLLAEAAIdkmTKKMQKTLENTkfrGNAPIIPVAAKPGGPEAPETEAPQGISE()}*

$111=201(164):
>Gtpbp1l consensus
{()IELRIAVLGNVDAGKSTLLGVLTQGELDNGrgrarlnlfrhkheieSGRTSSVSHEILGFDSKGEvvnysdsrgglsweeiceksSKVITFIDLAGHEKYLKTTIFGLTghLPDYAMLVVGANAGIVGMTKEHLGLALAL----NVPVFVVITKIDICPANVlqETLKQLTRILKSPGCRKIPVLVKNEDdVVTAASNFASGRVC()}*

$112=193(164):
>U5snRNP consensus
{()LIRNVALCGHLHHGKTCFVDCLIEQTHPEIrkrydqdlrytdilfteqeRGVSIKSTPVTLVLpDTKGKSYLFNIMDTPGHVNFSDEVTAALRLSDGVVLFIDAAEGVMLNTERLIKHAV----QERLAITVCINKIDRLILelklpptdayyklRHIVEEVNGLISMYSTDENLILSPLLGNVCFASSQYGICFTL()}*

$113=266(164):
>EFGlike consensus
{()KIRNIALVGHGGAGKTTLAEALLYATGAIDrlgrvddgntvsdydpeerkRGISISSSLAPLEWN----GHKINLIDTPGYVDFSGEVESALRVVDAAVIVVSAVDGVEVGTETLWELLEEY----GIPRFIFINKMDRENADFDevleelkerfgkkvvpiqlpigegegfkgvvdllsmkaypdgpgkvveipeelldeveeareelieavaetdeelmekyleggelteeelRAGLKKALREGKIVPVFCGSALKGIGVEELLDAIVRLLP()}*

$114=271(164):
>efG consensus seq for EFG/efGGold.cma
{()RYRNIGIMAHIDAGKTTTTERILFYTGKIHkigevhdgaatmdwmeqeqeRGITITSAATTCFWK----GHRINIIDTPGHVDFTIEVERSLRVLDGAVAVFCAVGGVEPQSETVWRQADKY----KVPRIAFVNKMDRTGADFFrvveqikdrlganpvpiqlpigaeddfkgvvdlvkmkaiiwdedlgatfeyeeipadlkeeaeeyreklieaaaeaddelmekylegeelteeeiKAAIRKGTLANEFVPVLCGSAFKNKGVQPLLDAVVDYLP()}*

$115=172(164):
>IF2 consensus seq for IF2/IF2Gold.cma
{()RPPVVTVMGHVDHGKTSLLD-YIRKTNVASgeaGGITQHIGAYQVETNKS--GKKITFLDTPGHAAFTAMRARGAKVTDIVVLVVAADDGVMPQTIEAINHAKA----ANVPIVVAINKIDKPEADPDKIEKIETVKNEllehelipedwgGDTQFVEISAKTGTGIDKLLEAILLQAE()}*

$116=180(164):
>LepA consensus  seq for LEPA/LepAGold.cma
{()NIRNFSIIAHIDHGKSTLADRLIQLTGGLSdremkaqvldsmdlereRGITIKAQTVRLNYKAKDgETYILNLIDTPGHVDFSYEVSRSLAACEGALLVVDASQGVEAQTLANVYLALEN----NLEIIPVLNKIDLPAADPerVKKEIEDVISGIDASDAILCSAKTGIGIEEILEAIVERIP()}*

$117=261(164):
>pcrf3 consensus
{()RRRTFAIISHPDAGKTTLTEKLLLFGGAIQeagtvkarksgrhatsdwmeiekqRGISVTSSVMQFPYR----DCVINLLDTPGHEDFSEDTYRTLTAVDSAVMVIDAAKGVEPQTRKLFEVCRLR----DTPIFTFINKLDREGRDPFelldeieevlgidcapitwpigmgkdfkgvydlyndevelfertiqveiikglddpeldellgedlaeqlreelelvrgagPEFDLEAFLAGELTPVFFGSALNNFGVQELLDGFVEWAP()}*

$118=238(164):
>tetRes consensus
{()KIINIGILAHVDAGKTTLTESLLYTSGAIKelgsvdkgttrtdsmelerqRGITIQAAVTSFQWE----DVKVNIIDTPGHMDFLAEVERSLSVLDGAILVISAKEGVQAQTRILFHALRKL----NIPTIIFINKIDRNGADLEkvyqdikeklsneiiikqsveltpearvieytddeqwdaviegndellekyvageplsdaelREEEERRVQQASLYPVYHGSAKTGIGIEELLEAITSLFP()}*

$119=192(164):
>TypA consensus seq for TYPA/TypAGold.cma
{()DIRNIAIIAHVDHGKTTLVDKLLKQSGTFReneevdervmdsndlekeRGITILAKNTAINWK----DTRINIVDTPGHADFGGEVERVLSMVDGVLLLVDAAEGPMPQTRFVLKKALEQ----GLKPIVVINKIDRPDARPdeVVDEVFDLFIELGAtdeqldFPVVYASALNGwasldlddpsEDMTPLFDAIIEHVP()}*

$120=159(164):
>BMS1 consensus
{()PPIVVAVVGPPGVGKTTLIKSLI----KNYTKQTLSEIRGPVTIVSGK-KRRLTFIECPNDI---NSMIDLAKVADLVLLLIDASFGFEMETFEFLNICQVH---GFPKIMGVLTHLDLFknnkqlRKTKKRLKHRFWTEVYQGAKLFYLSGMVHGEYQDREIHNLGRFI()}*

$121=164(164):
>T4_ObgEra consensus seq
{()EGPKVAIVGRPNVGKSTLFNALTGAEAAVYDFTTTTRDRGVVYVEVDGKGREFVLIDTPGLREGEGLGNKAIEEADVVLHVVDASGRDPRDDETEQDEEIADLGAEGKPVILVVNKADKDKEEEEKEELLERLEAGPGAPVVPISAKTGEGLDELLEALAEALE()}*

$122=228(164):
>Drg consensus
{()GDARVGLVGFPSVGKSTLLSKltGTYSEVAAYEFTTLTCVPGVIEYK----GAKIQLLDLPGIIEGAKDGKGRgrqviavARTCDLILMVLDATKPLGHKKLLEKELEGVGIRlnkkppniyfkkkdkgginitstvplthldektvksilheykihnadvliredatvddlidviegnRVYIPCIYVYNKIDQISIE--ELDRLAR-----IPHSVPISAHHKWNLDDLLEKIWEYLR()}*

$123=162(164):
>EngA1 consensus seq for ENGA/EngA1Gold.cma
{()MLPVVAIVGRPNVGKSTLFNRLTRERdAIVAdfPGVTRDRKYGKA----EWNGHEFILIDTGGIDGDDGLEKeiaeqalLAIEEADVILFVVDG-----RAGLTDADEEIaRELRKSNKPVFLVVNKVDNDKEDEAAYE---FYSLGLGEPF-PISASHGRGIGDLLDAVLEALD()}*

$124=171(164):
>EngA2 consensus seq for ENGA/EngA2Gold.cma
{()LPIKIAIIGRPNVGKSSLVNRLLGEErVIVSdiPGTTRDSIDIPFER----DGQEYVLIDTAGIRRRGKVTEvekfsvirtlKAIERADVVLLVIDA-----REGITEQDLRIAGFALEaGRALVIVVNKWDLDEEtrEEVKKELRRRLGFLDFAPIHFISALTGQGVGKLFESIDEAYE()}*

$125=184(164):
>aEngB consensus seq for ENGB/aEngBGold.cma
{()RMAEIIFVGRSNVGKSTLIRELTGKKVRRGkrPGVTRKPIEIEWG--------NHKITDMPGFGFmsgvpkevqerIKDEIVHYIednaDNIDVAVLVVDGKAAPEIIerwekrgEIPIDVEMFQFLRELGIPTIVAVNKMDKIKNVEEVLDflaEKLGLPWqQWDKVIAPISAKFGDNIEALKNRIRERIR()}*

$126=174(164):
>bEngB consensus seq for ENGB/bEngBGold.cma
{()DGPEIAFAGRSNVGKSSAINTLTnrknLARTSKTPGRTQLINFFEVNDG-------LRLVDLPGYgyakvpkemkAKWQKLLEEYLqkrESLKGVVVLMDIRHPLKDLDQQMLEWLVA----SGIPVLILLTKADKLKRGARKKQLLKVRKALAkfpaAVEVQLFSSLKKQGVDELRAKLDEWLG()}*

$127=258(164):
>EngD consensus seq for ENGD/EngDGold.cma
{()MGLKCGIVGLPNVGKSTLFNALTKAgaEAANYPFCTIEPNVGVVPVPdprldklaeiVKPKKIiptTMEFVDIAGLvkgaSKGEGLGNKFlanIREVDAIVHVVRCFEDDNITHVEGKVDPIRDIEtinteliladlesvekrlerlekkakggdkeakaelevlekilahleegkparslelseeekkllkqlqlLTAKPVLYVANVDEDGLAGNPYLDAVREIAAKEGAEVVVISAKIEaeIAELDDEEKAEFLEE()}*

$128=169(164):
>ERA consensus seq for ERA/eraGold.cma
{()RSGFVAIVGRPNVGKSTLLNALVGQKISItsrKPQTTRHRIRGIVTEDD----AQIIFVDTPGIKPKHrnalnrfmnRAAWSALKDVDLVLFVVDATKWGPGDEMILEKLK------AKTPVILVINKIDKDLVKDKEELLPLLQELSelmPFAEIVPISALKGDNVDELLDLLAKYLP()}*

$129=271(164):
>GbpX consensus seq for GBPX/GbpX_Gold.cma
{()XXILIGLVGKPNVGKSTFFNAatLADVEIANYPFTTIDPNVGVGYVRvecpckelgvkcnpnygkcVDGKRyVPVELIDVAGLvpgaHEGRGLGNKFlddLRQADALIHVVDASGttdaegkpteGYDPLEDIEFLEREIDMWiygileknwgkiarrhtaekakivealaeqlsgygvtesdvaralrrlgleadltkwsdedlerfaralrKISKPTVIAANKADHDADE--NIEKLKKEYEKPGYKVVPTSAEAELALRKAAKQGFIKYT()}*

$130=158(164):
>hflxA  consensus
{()EVPTVALVGYTNAGKSTLFNALTGAEVYaeDQLFATLDPTTRRLELPDG---REVLLSDTVGFIRDLphdlvaafRATLEEVREADLLLHVVDASDPDFEEQIEAVEEVLKELGADDIPQILVFNKIDLLDEE-------------GYPDAVFVSARTGEGLDELLEAIEERLA()}*

$131=195(164):
>Hsr1p consensus
{()EPLKLAVVGHTNTGKTSLLRTLTRDVgfGEVShrPSTTRHVEGARLSVDGE---ALLELYDTPGLEDaialldylerlerpgerldgPERlarfldsseAR-QRFEQeakvlrqllaSDAGLYVIDA---REPVLAK-YRDELAVLASCGKPLLPVLNFVASPQHREPEWREALARLGLHALVRFDSVAPP----FDGERRLYESLA()}*

$132=192(164):
>Hsr1_like consensus
{()KPVNILLVGRTGAGKSSLINTLFQAELAEVdvLPSTDAIQNYH---WQTPTGETLTLWDTPGYEQVNradlrELVLDYATTADLLLLVTPALDPALQMDVD-FLQDIRAE-VADLPAIAIVTQVDRLRPIREWQPPYDWQWGNrpkeiaireateyraellgdfcdQVLPLVTGDIKTGrsaWGVEALSLALLEAIA()}*

$133=176(164):
>MJ1126 consensus  seq
{()GFPTVALTGYTSAGKTTLFNALTGEnkEVDGEPFTTLSTKSRAIDING----KKVLLTDTVGFIDDLppqiieafHSTLEEIIYADVILLVIDGSDPleELKRKLKSSLETLREIGVSGKPIIIVLNKIDLIDDEEIEKKRDVLELAEnlykPITDVIPISALTGKNIEALKDVIFELLP()}*

$134=174(164):
>Nog1p  {|14(7)|}consensus
{()NTRTLLICGYPNVGKSSFINKVtrADVEVQPYAFTTKSLFVGH----FDYKYLRWQVIDTPGILDhpleerntIEMQAITALAHLRaAVLYFMDLSEQCgYSLEEQLKLFHSIKPLFANKPLIVVANKIDVKRIEDLseEDQKLLKDLEAEGVPVIEMSTLTEEGVMEVKNEACDRLL()}*

$135=173(164):
>obg consensus seq for OBG/ObgGold.cma 
{()VLADVGLVGFPNAGKSTLLSAVsaAKPKIADYPFTTLVPNLGV--VRYDD-GRSFVVADIPGLiegaHEGAGLGHRFLRHIErtrVLLHVVDISpldGRDPVEDYRTINNELEKYSPElaEKPRILVLNKIDLPDAEERLEELAERL--GWGGPVFPISAVTGEGLEELLRALADLLE()}*

$136=229(164):
>Rbg1 consensus
{()GVASVGFIGFPSVGKSTLMSKLtgQHSEAAAYEFTTLTTVPGQ--VMY-N-GAKIQILDLPGIiqgaKDGKGRGRQVIAVAKtchLIFIVLDV--NKPLTDKKIIENELEGFGIRinkeppnivfkkkdkgginitstvplthidhdeikavmseykissadiaircdatiddlidvleaksrsYIPVIYALNKIDSISIEELDLLYR-------IPNAVPISSEHGWNIDELLELMWEKLN()}*

$137=177(164):
>TGS consensus
{()GAGQVVLVGPPNVGKSSLLAAltGADPEVADYPFTTREPIPGMMEYED----VQIQLVDTPPLGEG-GMGPQLlavIRNADAIAIVLDLSA--DPVEQMEILLREFLERagikpngrapadaldpsLVWKRAIVIANKGDAPGSKENYEKLREAYGER--LKIFPVSAERGINLDALKEALYDALG()}*

$138=163(164):
>TrmE consensus seq for TRME/trmeGold.cma
{()EGLKVVIAGRPNAGKSSLLNALAGRErAIVTdiAGTTRDVLEEHIHIDG----MPLHLIDTAGLREtedeverigIERAW-KEIEQADLVLLVLDAAAAQSADDAG-LTPESLKAIDENLPVIVVRNKADLTGEK-------LGEDLEEVNAGIRLSAKTGEGIDLLREHLKQLIG()}*

$139=181(164):
>YfjP consensus
{()YEPVIGIMGKSGAGKSSLCNALFQGEVTPVsdvHACTREVQRFR----LSGGGHSMVITDLPGVGESRdrdaeyeALYRDILPELDLVLWLIKADDRALSVDEY-FWRHILHR-AGHQQVLFVVTQADKTEPCHEGIQPSPAqaqnirekteavfRLFRPVHPVVAVSARTGWELDTLVSALMTALP()}*

$140=164(164):
>T6_Simibi consensus seq
{()GPLVILVVGLQGSGKTTLLNKLAGALQKLRSTATVTVDAITQLKTLGEKGLDLVLIDTPGQLQFDELLDEELKKADAVLLVVDATTGEDAVALAKALKEALGLLGKGIPVIVVLTKLDLLDADGGAALSIEAEALLPDVKVVEVSAKTGEGIDDLGDALASRAL()}*

$141=192(164):
>FlhF consensus seq for FLHF/FlhFGold.cma
{()RGGVVALVGPTGVGKTTTLAKLAARYAlrhgakvALITTDTYRIGAHEQLKTYGRilgvpvhvvkdaeeladaleqlRNKDLVLIDTAGMSQRDRRLSEQLDTLLGagapieSYLVLSATsQGRDLQEVVEAFR-RLGL------SGCILTKLDE-TLSLGEVLSVVIRHKLP-VSYVTDGQRVpEDLEVATAKFLVSRAL()}*

$142=203(164):
>FtsY consensus seq for FTSY/FtsYGold.cma
{()KPFVILVVGVNGVGKTTTIGKLAKQFQAegkkvmLAAGDTFRAAAVEQLQVWGErngvpviaqphegadpasvafdavqaakaRGADVLIIDTAGRLQNKVNLMEELKKIKRvikkldpdapheVLLVLDATTGQNALSQAKLFKEAVGV------TGIVLTKLDG-TAKGGVVFAIADEFGLP-VKFIGVGEGIDDLRPFDAEEFVDALF()}*

$143=196(164):
>Srp54 consensus seq for SRP54/SRP54Gold.cma
{()GPAVILMAGLQGAGKTTTAGKLAKYLKEkkkkvlLVSADVYRPAAIEQLKTLGEqvgvpvfpsgtgqkpvdiakaaleeaklKGYDVVIVDTAGRLHIDEELMDELKAIkaavnpDETLLVVDAMTGQDAVNTAKAFNEALGL------TGVVLTKLDG-DARGGAALSIRAVTGKP-IKFIGVGEKLDALEPFHPDRMASRIL()}*

$144=210(164):
>SrpRB consensus seq for SRPRB/SrpRB_Gold.cma
{()SRRAVLLVGLCDSGKTLLFTRLLTGSY-RDTVTSITPNSATY-KLNNNKGKSLTLIDLPGHEKLrLKLLERLKSSARAIVFVVDSATfQKEVRDVAEFLYDILTDSEKLknkIPVLIACNKQDLFTAKSAKLIKQQLEKELntlrvtrsaalssldssstadaqlgkkgkefefsqlpLKVEFLEGSAKGGRGddgsadIDDLEEWIAKIAX()}*

$145=206(164):
>Ffh consensus seq for FFH/FfhGold.cma
{()GPAVILMAGLQGAGKTTTAGKLAKRLEKqkkkvlLVSADVYRPAAIEQLETLGEqigvpvfpsgagsgehemgngvqkpvdiaraaleeaklKGYDVVIVDTAGRLHIDEEMMDEIKAIKAavnpdeTLFVVDAMTGQDAVNTAKAFNEALGL------TGVVLTKLDG-DARGGAALSIRAVTGKP-IKFVGVGEKLDALEPFHPDRMASRIL()}*

$146=179(164):
>Aig1  consensus
{()PVRTLVLVGRTGNGKSATGNS-ILGRKAFKSKASASGVTSTCELQRTVtpDGRIINVIDTPGLFDlsvsaefIGKEIVKCLTLAKdgihAVLLVFSVRTRFSQEEEATLETLQVLFGSKIVdYMIVVFTGGDELEENNETLEDYLSDGCPEFlkEVLRLCGNRKVLFDNKTKDEGKKAKQ()}*

$147=243(164):
>Bdlp consensus seq
{()GDCPILVAGETSAGKSTLLNALLGEDLLpsSHLSCTSVICELKYGEQKRAVIHlkdgsepetiplegfedkytidleeakhlegedrqaeppvdkveifwplpllkgGIEIVDSPGLGESeamDELVKDYLPSAFAFIYVINSAN-----AGGVQEDRLLRNLLKFDPksAIFVCNKWDQVPESLIEPERQEVKqdtirklrecwranlaeycqvegPGLYESQVFFLSAKEALRARLKDFEALLDGT()}*

$148=335(164):
>Ch080  {|0(241)|}consensus
{()DPIYIGVFGSTGAGKSSLINAIIDQAmFLpvsGESACTSCIVQVSSGccEQYEAEIHflsdqewkeelknltkllhrtelgreeadawnrdesaaeaawklqavygngaerktyeellrakprvkiplsrvitlkaeeaeelsvkldpyirsqrrdwdgeaaemqiwplikhvevtlpksellpeGVVLVDIPGTGDFnskrDEMAKKYIDKCSVIWVVSDIER-----ASGGKAAEDLlgESIKacqdGfCRDVALVVTKTDKLHLPEylrerklgnqaiqsqReavleRNemiklqrtrilKEKLKRKLPADSKVLEASDLVYTVSAQEYWQQAFLTE()}*

$149=183(164):
>CyanoHypoA  consensus
{()GDYKVTLFGAGSSGKTSIARSLLKNIVGQTSAKIGTTKQInSYKIRIPILKRNINIVDTPGLFEPSKLGEErekatiiQASNSDLVLFVLD------QDINKYENYLIKELLKLGKKIIIVLNKCDLRSRDEnnlikeniisitsarkNKISVVQTIAVPQSSPYPKSDALNPVpEVGSLFREIIETLD()}*

$150=228(164):
>Dynamin consensus seq for DYNAMIN/DynaminGold.cma
{()DLPQIAVVGGQSAGKSSVLENFVGRDFlpRGSGIVTRRPLILQLINSKTEYAeflhckgkkftdfdevrqeieaetdrvtgtnkgispvpinlriysphvLNLTLIDLPGITKVpvgdqppdieyqiRDMILQFISRENSLILAVTPANTD--LANSDALKLAKEVDPQGLRTIGVITKLDLMDEGTDARDVLENKLLPLrrgYIGVVNRSQKDIEGKKDIRAALAAEVR()}*

$151=188(164):
>dynLike consensus
{()EPFRLVVVGEFKSGKSTLLNALLGEDVLpvGVTPTTAVITVLRYGEEKRATVYfadgkeveieyplpllkKVEIVDTPGLNSIneqhTELTLEFLPRADAVLFVLSADQ-----PLTESEREFLELIKDwGKKVFFVLNKADLLSEEELeevveFVREVLKELLGGDPPVFPVSAKLALRARLSGFPAFEDFL()}*

$152=220(164):
>Ehd  consensus
{()NKPMVLLVGQYSTGKTTFIRYLLEQDFpgmRIGPEPTTDSFIAVMHGDTEGVIPgnalvvdpkkpfrklnafgnaflnrfmcsqlpnpvleSISIIDTPGILSGekqrisrgydfAAVLEWFAERVDRIILLFDAH----KLDISDEFSEVIKALKGhEDKIRVVLNKADQIDTQQLMRVYGALMWSLGKvintpevVRVYIGSFWSQPLLIpDNRKLFEAEEQ()}*

$153=147(164):
>EutP consensus seq for EUTP/EutPGold.cma
{()SKKRIMFIGPVGCGKTTLTQALQGEEIL--YKKTQAVEFND------------NDIDTPGEYLenrrLYSALITTAQDADVIALVQDATDPESR-----FPPGFASIFNK--PVIGVITKTDLAMPDADIEAARKLLLEAGAKEIFEISAVDPQGVEELVDYLASLTK()}*

$154=163(164):
>FoeB consensus seq for FEOB/FeoBGold.cma
{()KKLTIALVGNPNVGKTTLFNALTGARQKVGNWPGVTVE--KKEGKFKHKGHEVTLVDLPGTYSLTPYSLdeqvardyLLSEKPDVIINVVDATN------LERNLYLTLQLLELGIPVVVALNMMDEAEKRGIRID-IDKLSKELGVPVVPTVARRGEGIDELKEAIDELLA()}*

$155=183(164):
>FungalHypA consensus
{()PDGLIAVMGGTGSGKSTFINAISGDVADVGHGLESCTAEVQEYEFFMLNGKRVTLVDTPGFDDTNKSDLEILKEIAAwlaaeydevklsgIIYLHNISDPRVGGSSRRNLRMFKKLCGKDalKNVVVVTTFWDEVDLEEGEERETELKSkdkfLKELVDGGATFARFGDYPDGAEFPSAWSIV()}*

$156=175(164):
>Gima  consensus
{()SELRIVLVGKTGVGKSATGNTILGRKaFESKLSA-QSVTKTCQKESGEWNGRSVSVVDTPGLFDtelsneeiqkeISRCVSLSAPGPHAFLLVLQLGRFTEEEQKTVKLIQEIFGEEALKYTIVLFTRGDDLEGQSLEDYLEESDSLRklvqECGGRYHAFNNTGEEDR----TQVSELL()}*

$157=259(164):
>gpn2 consensus 
{()TRFGQLVIGPAGSGKSTYCSGMQQHLEAlGRKVQVVNLDPAAEHFpypcavdireLITLEDVmeelslgpnggliycmeyleenldwleeklgeledDYLLFDCPGQIELYTHHPVLRNIVEqlqqwnfrlCAVHLVDSqFCTDPSKFISGLLAALSAMLQLELPHVNVLSKMDLLSkygklafnldyytevqdlsylledldsdpfskkfkklneAICELIEDYSLVSFLPLDVQDEESMNRLLSHIDKANGYGEDAE()}*

$158=177(164):
>LRRK consensus seq
{()NRMKLMIVGNPGSGKTTLLEQLQKGKKSqlGHNIATVGIDVKDWEIQIRagsKGKVVFNVWDFGGQEEYYSTHQCFLTQRALYLVVWNLSLGEEEVaALKPWLLNI-KARAPNSPVILVGTHLDVIDEKQrkeciakLRKELCRKPGFPDIKDYHEVSCKTeLEGIEKLRKLIYDVSL()}*

$159=230(164):
>MFN  consensus
{()RHMKVAFFGRTSNGKSSVINAMLWDKVLpSGIGHTTNCFLSVEGTDGDEAYLmtegseekksvktvnqlahalhqdkdlkagslvrvfwpkskcallrdDLVLVDSPGIDVTteldSWIDK-FCLDADVFVLVANSES-----TLMQTEKQFFHKVSErlsKPNIFILNNRWDASASEPEymedvrRQHmERCTSFLVDELkvvdraeagdRIFFVSAKEVLSARIQKAQGMPEGG()}*

$160=177(164):
>PlantHypoB consensus
{()SLRFAAFIGPENAGKTTLINSILGENVGGVGFTTHTTAATPYRFRD-----DIFLVDFPGTDgggdraHLSKIWEDYEKVADLCVVVLNFGGDTSRA--AQVFPRIARSRMCG-NVVLVINRVDSvlngsrnspvwaeysADKVEQLKISIAENSGLPADRVFFSVSRTNEELEETTRQLLKERL()}*

$161=178(164):
>RagCD consensus
{()SKPRILLMGLRRSGKSS-IQKVVFHKMSpnetLFLESTNKIVKDDISNS---SFVNFQIWDFPGQIDFFDPtfdYEMIFRGTGALIFVIDAQ-DDYMEALARLHLTVTRAYkvNPDINFEVFIHKVDGLSDDHKietqRDIHQRANDDLADaglekihLSFYLTSIYD-HSIFEAFSKVVQKLI()}*

$162=176(164):
>Rag consensus seq for RAG/RagGold.cma
{()MKKKVLLMGKSGSGKTS-MRSIIFANYIARDTRRLGATIDVEHSHVRfLGNLVLNLWDCGGQEAFMENyftsqRDNIFRNVEVLIYVFDVESRELEKDMHYYQSCLEAILqnSPDAKIFCLVHKMDLVQEDQRDLIFKEREEDLRRlskpleCTCFRTSIWD-ETLYKAWSSIVYQLI()}*

$163=174(164):
>RarD consensus seq for RARD/RarDGold.cma
{()AAVKIVVAGGFGVGKTTFVGSVSEIEPLRTEavmtEASAGVDDLSGVPDkttttvamdfgriTLDDDLVLYLFGTPGQDRFWFMWDDLVRGALGAVVLVDTRRLEdSFAAVDYF-----EH--RGLPFVVAVNCFD-GAPRYPPEEVREALDLPPDVPVVTCDARDRESVKQVLITLVEHAL()}*

$164=168(164):
>Roco  {|10(4)|}seq
{()NEAKLLLVGEGGVGKTSLAKRLIDNTFDEDEPQTEGINIKQWNFPNEkgcetdvnNKDFRLNIWDFGGQEIYHATHQFFLTKRSLYLLVLDSRKEEDF---EYWLKII-ELFGGDSPVIIVGNKKDERPSLDINRKGLREKFPNIKDAFLETSCKTNRGIDELKEAIKQEIS()}*

$165=220(164):
>Septin consensus
{()FEFNLMVVGESGLGKSTLINTlFLTDLYKERkipserIEKTVEIEAITVEIEENGVRLRLTVVDTPGFGDqinnedcwqpivdyiddqFEAyLREESRInrknipdnRVHCCLYFIS----PTGHGLKPLDIEFMKRLHEKVNIIPVIAKADTLTPEELARFKKRIMEEieehgikiyqfpeddeddeetkeenreLRESIPFAVVGSN-EEVEVNGKKVRGRQY()}*

$166=186(164):
>CoSyn consensus
{()M-KLVIVAGPPSAGKTSVILHTIKQLKKEGnKPAVVKIDCLYtddderygklgiptlkglsgdlcpdhfaiynleeMVEWAEKEGADLLIVETAGLCLRCAPYtknSLG-------ICVIDATS--------GPNTPLKVGPMLTLADIVVITKGDIVS--QAEREVFRERVLEVNpkCTIIEVNGLTGQGCRELSEEIMEAPE()}*

$167=197(164):
>ureG consensus
{()GPLRVGIGGPVGSGKTALLEALCKALRDRYSLAVVTNDIYTKEDAefltrngalpperiigvetggcphtairedasinlaaveeleARFPDLDLVFIESGGDNLAATFSPELA---DLTIYVIDVAA--------GDKIPRKGGPGITKSDLLVINKTDLAPYVGADLEVMERDAKRMRggRPFVFTNLKTGEGLDEVIDFIERQGL()}*

$168=212(164):
>ifi44 consensus
{()SQIRILLLGPVGAGKSSFFNSVNSIFQGhVTSQALVGSDgtsITTKYRTYSIKDgkdgkpLPFVLCDTMGLEEqgaglciddipyilkghvpdryqfnpekpitpkhpGYITSPSLKDRIHCVVYVIDANSISLLSDklIEKLKAIRKKVNDCGIPQVVLLTKVDEACPLVKDDLLNVYRSKTIKSKVEEVSSKLGVPVSNILpVKNYSSEL()}*

$169=201(164):
>CobW consensus
{()KIPVTVLTGFLGAGKTTLLNHILTNRHGKRIAVIVNEFGEVgidadlvvsrdeelvelsngcicctvredllravERLAERRGRFDYIVIETTGLADPApvaqtFFVDDELRDrarLDAVVTVVDAKHFL------GDlADSEEAVDQIAFADVIVLNKTDLVDEEELAALEARLRALNPRAKILRTERGEVPLAELLGTGAFDLDR()}*

$170=187(164):
>HypB consensus seq for HYPB/HypBGold.cma
{()GILALNLVSSPGSGKTTLLERTIEALKdklpIAVIEGDQQTSNDAeriratgvpaiqintgkgchldahmvhhALHRLPLDDLDLLFIENVGNLVCPASFDLGE---HAKVVVLSVTE--------GEDKPLKYPHMFRAADLMLINKIDLLPYVDFDVEKCIAYARRVNpdIEVIEVSAKTGEGMDAWLAWLEAQRA()}*

$171=194(164):
>TOC34 consensus seq for TOC34/Toc34Gold.cma
{()NSLTILVLGKGGVGKSSTVNSIIGEQVVsVSAFQSETLRPVMVSRTVGG--FTINIIDTPGLVEggyvndqALESIKRFLKNKTIdVVLYVDRLDVYRVDELDKqVLRAITDSFGKEIwrNAIVVLTHAQSSPPDGLSYDTFVSQRSHALqqtirqgagdkklendsaipVVLVENSGRCRKNRKGEKVLPNGQAW()}*

$172=245(164):
>XpaBP consensus seq for XPABP/XpaBPGold.cma
{()KPVCIIVLGMAGSGKTTFVQRLTAHLHSKKKPYVINLDPAVHEVpfpanidirdTVKYKEVmkqyglgpnggivtslnlfatkfdqvikliekaqnksKYVLIDTPGQIEVFTWSASGTIITEalassfptVVAYVMDTpRSTNPVTFMSNMLYACSILYKTKLPFIVVFNKTDIIDHSFAVEWMQDFEAFQdalnqettymsnltrsmslvldefySSLRVVGVSAVTGTGLDEFFVAVESAAE()}*

$173=164(164):
>T7_Gbp1 consensus seq
{()PVVVVGVVGAYRSGKSFLLNQLLGGEGGGSDGETKGIWIWCTPVEVDGKKVAVLLLDTEGTEDVGKSWIFALATALSSILVYNLSGTVSEADLSELSEATERGAFEGPFQSLVGTVRDFSDGKEVDGGAGEALAFTNGSCFSLPSPGLGEATACLFDGSAREID()}*

$174=225(164):
>Atlastin-1 consensus seq
{()EVVVVSVAGAFRKGKSFLLDFMLRymynqdssdwlgdpnepltgfSWRGGSERETTGIQIWSEVFLidkPDGKKVAVLLMDTQGAFDSQStvkdcATVFALSTMTSSVQVYNLSQNIQEDDLQHLQLFTEYGRlameeiFQKPFQTLMFLVRDWSFPYEasygAEGGKKFLEKrlqvsenqheelqnvrkhihscFSNIGCFLLPHPGLKVATNPNFDGRLKDID()}*

$175=223(164):
>HuGbp1 consensus
{()PVVVVAIVGLYRTGKSYLMNKLAGknkgfSLGSTVQSHTKGIWMWCVPH-PKKPNHTLVLLDTEGLGDVEKgdnkndSWIFALAVLLSSTFVYNSMGTINQQAMDQLHYVTELTeliraksspdenedgvedsaEFVSFFPDFVWTVRDFTLELELDGQPITEDEylenalklkqgtspkvqnfnlprecirkfFPKRKCFVFDRPTHDKKLAQLEKLSEEELD()}*

$176=211(164):
>PlantGbp1 consensus seq
{()PIAVVGVIGPYRSGKSFLLNQLLSlscdkgfGVGHMRDTKTKGIWIWGTPVEmdIDGSKVSVLYLDTEGFESVGKSnvyddRIFALATVLSSVLIYNLPETVREADISRLSFAVEIAeefygrvkgqdVAFEPAKLLWLIQRDFLQGKSVQQMVNEALQrvpnengdkyidevnqirdslavmGNNSTAFSLPQPHLQRTKLCDMD--DRELD()}*

$177=178(164):
>sey1 consensus seq
{()NYHLISVFGSQSTGKSTLLNHLFGTnfdvmDESERQQTTKGIWM------SKNKRDNILVMDVEGTDGRErgedqdferKSALFALAT--SEVLIVNIWEHqvglYQGANMGLLKTVFEVNLQLfgkdKHKSLLLFVIRDHVGVTPLSNLQATLTQDLERIWSSLSKPAGLENSQIEDYFDFAFYG()}*

$178=164(164):
>T8_OtherGTPases consensus seq
{()AALTVGFTGSSGGGKSTFINALGGRGTEAGEASAGRRAGDCTPESCEAKGFNVTLWELGGGGSSDTLEADDTEETDSFVLVLSTGAPNDLWFTEGDALQATKKGKMGIPDYIVGTKADGDNSDGANRAAAEQKAGYSGAPVFTCSAKSGEGYDELKEAETAHKA()}*

$179=206(164):
>DynLIC consensus seq
{()AEKTVFFIGSKNGGKTTIILRFLDRDeppkpTLALEYSYGRRAGHNTP------KDIAHFWELGGGTSLLQLISIpittDTLRTFSVVLVLDLSKPNDLWPTMENLLQATKshvdkvlgktnpkaveemrqrawervgkdhpdlelLDPFPIPLVIVGSKYDVfQDFDSEKRKVIcrtlRFVAHYYGASLMFYSSKS-EALLKKLRDVINHLA()}*

$180=240(164):
>dlic consensus
{()SGKNVLVLGEDGSGKTTLIAKLQGAeeykkGRGLEYLYLNVHDEDRDD------QTRCNVWILDGDLYHKGLLKFalsaESLKDTLVILVVDMSRPWTALESLQKWASVLRehidklkippeemreleqklvkdfqeyvepgedLQGSPqrrgpltsgsdddsvalplgdnvlthnlgIPVLVVCTKCDAiSVLEKEhdyrdehfdfIQSHIrkfclQ-----YGAALIYTSVKENKNLDLLYKYIVHKLY()}*

$181=183(164):
>Iigp1 consensus
{()APLNIAVTGESGAGKSSFINALRGVGheeegaaPTGVVETTMKRTPYPHP-----KFPNVTLWDLPGIGTTnfppeDYLEEMKFEEYDFFIIISSTR------FKENDAKLAKAIQKMGKKFYFVRTKIDSDLSNEkkskpssfneekvlqsirDNCSENLQKAGVSEPPVFLVSNFDLSDYDFPKLEETLLKD()}*

$182=206(164):
>MeaB  consensus
{()NALRIGITGVPGVGKSTFIEALGMMLREQGHRVAVLAVDPSSPRSggsilgdktrmerlsrdpnafirpspsrgtlggvarktreaillCEAAGFDVILVETVGVGQSETAVADMV---DTFLLLLLPGA--------GDELQGIKKGIMEIADLIVVNKADGDNRPGARRAAAEYRSALHLLrpkspgwrpPVLTCSALEGEGIDELWEAIEAHRA()}*

$183=215(164):
>FungalHypB  {|6(66)|}consensus
{()KRFRVLIIGRANAGKTTILQRVC-NTTEQPKPTAQRGEHDIENEMIFESNPAFVFHDSCGFEagrtseldkvkdflQKRSTNKNLEDHLHVIWYCIPINDEAGRPFTRAELnfFAMKDEcGTGRVPVIVLFTKADMLDAQVQETIKHLVDtgmdvedaankapeesvarfeekfgqqlykkkyppkdhvyFRDMQNPTSDCSELLRKTAAALK-----NTL()}*

$184=164(164):
>T9_PermutedGTPase consensus seq
{()KGKTAYFVGQSNVGKSTLINRLAGGKIAEKPGTTKGTTTHAEGKGDPGGGGSYELIDTPGIREANEEVKENAGNSDQVVNVFDAEDDNGSNNPGRDEFAAEAXXXGGNPRLKVLNKADLLDDSVTKGEETQAIREAQGYDVLATSAKTGEGVDELIEAAKGKAS()}*

$185=252(164):
>ArchaealMMR1 consensus  seq
{()EKVKVALIGYPNVGKSTIINVLKGKHAVGtapIPGYTKGKQLIRLSKK-------IWLLDSPGVVPiddfdelvikggfpadkieepvkpalkligriletrkealtekfgitefeseedilrkigerrgliraggevdieetarwflrewqtgrftlfgkeeerkkAWRVVKEVIDEADIVVEVVDARDPIGTRNRKLERLVLE----SGKKLLIVMNKADLVP----KEWAEEYKRK-SEIPVVFISARERKGTGILRKEIKKLAK()}*

$186=282(164):
>cd014 consensus
{()YRGDVYLVGCTNVGKSTLFNTLLesdyckakasDLVDRAtisPwPGTTLNLLKFPILrpspyrlfqrfkrlkseraqaeedekereqqaleglkkhaylvgrvgrtfdrreeqkdevafdsfafdmgnepvmvaskptttlnltaeeYKD-----AHWFYDTPGVMQPDqildvqvspeqyVELVSAIQDKPaLVLLMVDLLDFPCSIWPGLPALV------GPKRVIVVGNKVDLLPQDSpgYLQRIRERLWRDciraglgsrtNIKDVSLISAKTGYGVEELITALQRSWR()}*

$187=177(164):
>Nos1p consensus seq
{()XGRDVYILGSANVGKSAFISALLktmaYKDPVAaaaqkykpiqsAvPGTTLGPIQ--IEafLGG------GKLYDTPGVHLHEelREKLSHLRHEKaLIVKLVDIVDFNGSFLARVRDLA------GANPIILVITKVDLLPRDTDLNCVGDWVVEAtvkkklNVLSVHLTSSKSLVGITGVISEIQQEKK()}*

$188=161(164):
>Nug1_up consensus
{()RSISVGVIGYPNVGKSSVINALTarlnggSSKACPvgaEAGVTTSLREVKIDNK-------LKLLDSPGIVFDKVFKQV-VDAADVVLYVLDARDPEGTRSKDVERAVMAADG-GSKRLILILNKIDLVPPPVLKQWLNHLRR---SFPTLPLRASNGAPNAHSFNHKQLTVK()}*

$189=209(164):
>PlantHypo_up consensus
{()PRGNVWVIGAQNAGKSTLINAFAkkegGKVTKLteapVPGTTLGILRIGGVLPA-----KAKLYDTPGLLHpyqmsmrlNReeqkmveirkelkrliGTRLMKPSGGRtVVVMVVDCVDFDGSFpkraakslfkalegggsawkegKGNLPRLV------------LVATKVDLLPSQISPTRLDRWVRHRakaggapKLSGVHLVSARKDLGVRNLLDDIKELAG()}*

$190=165(164):
>YjeQ_up consensus
{()KGKTSVFVGQSGVGKSTLLNALLpelelkTGEISEKLGRGRHTTTHAELYPLPGGGL---LIDTPGFREFglwhrkNELVRPIAANIDQVLIVFALEPDFNLNLLDRYLVAAEA---AGIEPVIVLNKIDLLDD-----EELLAIYRAIGYPVLEVSAKTGEGLDELKELLKGKTS()}*

$191=158(164):
>YlqF_up consensus
{()RPIRAMIVGIPNVGKSTLINRLAGKKIAKtgnKPGVTKGQQWIKLGKG-------LELLDTPGILWpghmakARREIKENLKLVDVVIEVLDARIPLSSRNPMIDEII------GDKPRLKVLNKADLADPEVTKQWIDYF--EEQGIKALAINAKEGKGVKKIIDAAKKLAP()}*

$192=178(164):
>YqeH_up consensus seq
{()KGRDVYVVGVTNVGKSTLINRIIkeitGEKDVIttsRfPGTTLDKIE--IPLDD-----GSYLYDTPGIIHHNeiqdvsltdddfLRLLHEIGDSDaLVVNVVDIFDFNGSWIPGLPRFV------GGNPVLLVGNKKDLLPKSVKRGKVTQWLRERakeeglRPVDVVLTSAQKGHGIDELIEKIEEYRX()}*

_0].
